# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myproto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\x12\x07myproto\"$\n\rStringRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"!\n\x0bVectorReply\x12\x12\n\x06vector\x18\x01 \x03(\x01\x42\x02\x10\x01\x32I\n\x07MyProto\x12>\n\x0cReturnVector\x12\x16.myproto.StringRequest\x1a\x14.myproto.VectorReply\"\x00\x42\tZ\x07myprotob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007myproto'
  _VECTORREPLY.fields_by_name['vector']._options = None
  _VECTORREPLY.fields_by_name['vector']._serialized_options = b'\020\001'
  _STRINGREQUEST._serialized_start=26
  _STRINGREQUEST._serialized_end=62
  _VECTORREPLY._serialized_start=64
  _VECTORREPLY._serialized_end=97
  _MYPROTO._serialized_start=99
  _MYPROTO._serialized_end=172
# @@protoc_insertion_point(module_scope)
