# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import myproto_pb2 as myproto__pb2


class MyProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReturnVector = channel.unary_unary(
                '/myproto.MyProto/ReturnVector',
                request_serializer=myproto__pb2.StringRequest.SerializeToString,
                response_deserializer=myproto__pb2.VectorReply.FromString,
                )


class MyProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReturnVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReturnVector': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnVector,
                    request_deserializer=myproto__pb2.StringRequest.FromString,
                    response_serializer=myproto__pb2.VectorReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myproto.MyProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReturnVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myproto.MyProto/ReturnVector',
            myproto__pb2.StringRequest.SerializeToString,
            myproto__pb2.VectorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
