version: "3.5"
services:
  server:
    container_name: server
    image: server
    build: "./"
    restart: unless-stopped
    command: "./server"
    ports:
      - "8088:8000"
    volumes:
      - ./images:/partypoint/static/images
    depends_on:
      - redis
      - postgres
  
  postgres:
    image: postgres:10.5
    restart: always
    env_file:
      - /home/artyom/DiplomaBackend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5439:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /diplomaVolumes/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"