version: "3.5"
services:
  server:
    container_name: server
    image: server
    build: "./"
    restart: unless-stopped
    command: "./server"
    ports:
      - "8080:8080"
    volumes:
      - server-storage:/home/ubuntu/static/images
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - server-storage:/home/ubuntu/static/images
      - web-root:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - "server"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artyomsh01@yandex.ru --agree-tos --no-eff-email --staging -d bmstusa.online -d www.bmstusa.online

volumes:
  server-storage:
  certbot-etc:
  certbot-var:
  web-root: