version: "3.5"
services:
  server:
    container_name: server
    build: "./"
    restart: unless-stopped
    command: "./server"
    ports:
      - "8080:8080"
    volumes:
      - server-storage:/home/ubuntu/static/images
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - server-storage:/home/ubuntu/static/images
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    depends_on:
      - "server"

  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot

volumes:
  server-storage: