version: "3.5"
services:
  server:
    build: "./"
    restart: unless-stopped
    command: "./server"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"