version: "3.5"
services:
  server:
    container_name: server
    image: server
    build: "./"
    restart: unless-stopped
    command: "./server"
    ports:
      - "8080:8080"
    volumes:
      - server-storage:/home/ubuntu/static/images
    depends_on:
      - redis
      - postgres
  
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /diplomaVolumes/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
  
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - server-storage:/home/ubuntu/static/images
      - web-root:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - "server"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artyomsh01@yandex.ru --agree-tos --no-eff-email --force-renewal -d bmstusa.online -d www.bmstusa.online

volumes:
  server-storage:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/DiplomaBackend/dhparam/
      o: bind