// Code generated by MockGen. DO NOT EDIT.
// Source: internal/microservices/event/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckKudaGoFavourite mocks base method.
func (m *MockRepository) CheckKudaGoFavourite(userID, eventID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKudaGoFavourite", userID, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckKudaGoFavourite indicates an expected call of CheckKudaGoFavourite.
func (mr *MockRepositoryMockRecorder) CheckKudaGoFavourite(userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKudaGoFavourite", reflect.TypeOf((*MockRepository)(nil).CheckKudaGoFavourite), userID, eventID)
}

// CheckKudaGoMeeting mocks base method.
func (m *MockRepository) CheckKudaGoMeeting(userID, eventID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKudaGoMeeting", userID, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckKudaGoMeeting indicates an expected call of CheckKudaGoMeeting.
func (mr *MockRepositoryMockRecorder) CheckKudaGoMeeting(userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKudaGoMeeting", reflect.TypeOf((*MockRepository)(nil).CheckKudaGoMeeting), userID, eventID)
}

// CreateKudaGoEvent mocks base method.
func (m *MockRepository) CreateKudaGoEvent(placeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKudaGoEvent", placeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKudaGoEvent indicates an expected call of CreateKudaGoEvent.
func (mr *MockRepositoryMockRecorder) CreateKudaGoEvent(placeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKudaGoEvent", reflect.TypeOf((*MockRepository)(nil).CreateKudaGoEvent), placeID)
}

// GetFavouriteKudagoEventsIDs mocks base method.
func (m *MockRepository) GetFavouriteKudagoEventsIDs(userID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavouriteKudagoEventsIDs", userID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavouriteKudagoEventsIDs indicates an expected call of GetFavouriteKudagoEventsIDs.
func (mr *MockRepositoryMockRecorder) GetFavouriteKudagoEventsIDs(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavouriteKudagoEventsIDs", reflect.TypeOf((*MockRepository)(nil).GetFavouriteKudagoEventsIDs), userID)
}

// GetPeopleCount mocks base method.
func (m *MockRepository) GetPeopleCount(placeID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeopleCount", placeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeopleCount indicates an expected call of GetPeopleCount.
func (mr *MockRepositoryMockRecorder) GetPeopleCount(placeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeopleCount", reflect.TypeOf((*MockRepository)(nil).GetPeopleCount), placeID)
}

// SwitchEventFavourite mocks base method.
func (m *MockRepository) SwitchEventFavourite(userID, eventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchEventFavourite", userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchEventFavourite indicates an expected call of SwitchEventFavourite.
func (mr *MockRepositoryMockRecorder) SwitchEventFavourite(userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchEventFavourite", reflect.TypeOf((*MockRepository)(nil).SwitchEventFavourite), userID, eventID)
}

// SwitchEventMeeting mocks base method.
func (m *MockRepository) SwitchEventMeeting(userID, eventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchEventMeeting", userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchEventMeeting indicates an expected call of SwitchEventMeeting.
func (mr *MockRepositoryMockRecorder) SwitchEventMeeting(userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchEventMeeting", reflect.TypeOf((*MockRepository)(nil).SwitchEventMeeting), userID, eventID)
}
