server:
  port: "8000"
  name: https://diplomatest.site

postgres:
  port: 5432
  host: "postgres"
  #user: "a_shirshov"
  #database: "Diploma"

redis:
  addr: "redis:6379"
  db_id: 0

img_path:
  "/home/ubuntu/static/images"