server:
  port: "8080"
  name: "http://45.141.102.243"

postgres:
  port: 5432
  host: "45.141.102.243"
  user: "a_shirshov"
  database: "Diploma"

redis:
  addr: "redis:6379"
  db_id: 0

img_path:
  "/home/ubuntu/static/images"